### ISSUE TITLE
Backdrop turn screen entirely black on "avboka" dialog in booked Times

### ISSUE THREAD

**Issue by lundsnation** [lundsnation/laundry_booking#109]
Only appears to be happening in safari, se attached video 
https://user-images.githubusercontent.com/118682658/213894178-24087574-a419-40e9-a9d8-a765ecf43a01.mov

**Comment by lundsnation** [comment]
![image](https://user-images.githubusercontent.com/118682658/213894256-640a7760-84d7-4bab-8b0e-7428659c6864.png)
![image](https://user-images.githubusercontent.com/118682658/213894262-606d5d8d-8afd-4506-81b3-6bec63edc09e.png)

**Comment by adicreson** [comment]
Solved in #113
