### ISSUE TITLE
Alter the GDPR-dialog window, based on viewport

### ISSUE THREAD

**Issue by lundsnation** [lundsnation/laundry_booking#61]
If a user is prompted with the GDPR-dialog, the modal will stretch the ful width of the screen for mobile compatibility, alter this to display as a smaller dialogue if viewport is bigger than sm. Alternatively make the text a scrollable item

**Comment by lundsnation** [comment]
Added in #66

**Comment by lundsnation** [comment]
Not fixed in #66

**Comment by Axelb531** [comment]
Fixed in #80
